---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: cv-template.tex
geometry: margin=1in

title: "CV"
author: John Tipton

jobtitle: "Assistant Professor, Department of Mathematical Sciences"
address: "309 Science and Engineering Building · University of Arkansas · Fayetteville, AR, 72701"
fontawesome: yes
email: jrtipton@uark.edu
# github: jtipton25
# phone: "+970 231 9494"
web: www.jrtipton.com
updated: yes

# keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Employment

## University of Arkansas \hfill Department of Mathematical Sciences

Assistant Professor \hfill 2017--present

    
    
## Colorado State University \hfill Department of Statistics

Postdoctoral Researcher \hfill 2016--2017     
Graduate Research Assistant \hfill 2009-2016


# Education

## Colorado State University, Ph.D. Statistics \hfill 2016

## Colorado State University, M.S. Statistics \hfill 2011

## Colorado State University, B.S. Mathematics and Zoology \hfill 2005

# Assignment

Assigned to 40\% teaching, 40\% research, and 20\% service. My full teaching load is 2 courses per semester including development of new course materials. My research is focused on applied statistics and methodological statistics research with an emphasis on spatial, paleoclimate, and environmental applications.


# Publications

## Published and in Review

* [15] John Tipton, Glenn Sharman, and Sam Johnstone (2020+). Estimation of Sediment Mixing Distributions with Uncertainty Quantification using Bayesian Nonparametric Modeling. In revision. [[R code on gitHub]](https://github.com/jtipton25/mixing-manuscript)

* [14] Ann Raiho, Michael Dietze, Andria Dawson, Christine R. Rollinson, John Tipton, and Jason McLachlan. (2020+). Towards understanding predictability in ecology: A forest gap model case study. Global Change Biology. In review. [[bioRxiv]](https://www.biorxiv.org/content/10.1101/2020.05.05.079871v2.full.pdf)

 * [13] Manuel Chevalier et. al (2020). Pollen-based climate reconstruction techniques for late Quaternary studies. Earth-Science Reviews. [[paper]](https://doi.org/10.1016/j.earscirev.2020.103384)

* [12] John Tipton, Mevin Hooten, Connor Nolan, Bob Booth, and Jason McLachlan (2019). Predicting unobserved climate from compositional data using multivariate Gaussian process inverse prediction. The Annals of Applied Statistics. Vol 13, No. 4, pp. 2363-2388. [[paper]](https://projecteuclid.org/euclid.aoas/1574910048)[[arXiv preprint]](https://arxiv.org/abs/1903.05036)[[R code on gitHub](https://github.com/jtipton25/compositional-inverse-prediction)

* [11] Connor Nolan, John Tipton, Robert K. Booth, Mevin B. Hooten, and Stephen T. Jackson (2019). Comparing and improving methods for reconstructing water table depth from testate amoebae. The Holocene. [[paper]](https://journals.sagepub.com/doi/10.1177/0959683619846969)[[R code on gitHub]](https://github.com/jtipton25/BayesComposition)

* [10] Connor Nolan et. al. (2018) Past and future global transformation of terrestrial ecosystems under climate change. Science. Volume 361, Issue 6405, August 31, pp. 920-923. [[paper]](http://science.sciencemag.org/content/361/6405/920)

* [9] Erin Belval, Yu Wei, David Calkin, Crystal Stonesifer, Matt Thompson and John Tipton (2017). Studying interregional wildland engine assignments for large fire suppression. International Journal of Wildland Fire. [[paper]](http://www.publish.csiro.au/WF/WF16162)

* [8] John Tipton, Mevin Hooten, and Simon Goring (2017). Reconstruction of spatio-temporal temperature processes from sparse historical records using probabilistic principal component regression. Advances in Statistical Climatology, Meteorology and Oceanography. [[pdf]](http://www.adv-stat-clim-meteorol-oceanogr.net/3/1/2017/ascmo-3-1-2017.pdf) [[R code on gitHub]](https://github.com/jtipton25/observer)

* [7] Trevor Hefley, Kristin Broms, Brian Brost, Frances Buderman, Shannon Kay, Henry Scharf, John Tipton, Perry Williams, and Mevin Hooten (2017). The basis function approach to modeling dependent ecological data. Ecology. [[pdf]](http://www.stat.colostate.edu/~hooten/papers/pdf/Hefley_etal_Ecology_2017.pdf) [R code [S3](http://onlinelibrary.wiley.com/store/10.1002/ecy.1674/asset/supinfo/ecy1674-sup-0003-AppendixS3.pdf?v=1&s=1ec1d5c25a2287b36029dd315184190d0c5f8c04), [S4](http://onlinelibrary.wiley.com/store/10.1002/ecy.1674/asset/supinfo/ecy1674-sup-0004-AppendixS4.pdf?v=1&s=4c29dbe01f5521638315a3159c43971b30822d0c), & [S5](http://onlinelibrary.wiley.com/store/10.1002/ecy.1674/asset/supinfo/ecy1674-sup-0005-AppendixS5.pdf?v=1&s=8bbe6b6f8165283cf91df19b528a34b8ee1ee6d4)]

* [6] John Tipton, Mevin Hooten, Neil Pederson, Martin Tingley and Daniel Bishop (2016). Reconstruction of late Holocene climate based on tree growth and mechanistic hierarchical models. Environmetrics, 27(1):42-54. [[pdf]](http://onlinelibrary.wiley.com/doi/10.1002/env.2368/abstract) [[R code on gitHub]](https://github.com/jtipton25/Mechanistic-Tree-Ring)

* [5] Douglas Silver, Brett Johnson, William Pate, Kyle Christianson, John Tipton, James Sherwood, Brian Smith, Yun Hao, and Patrick Martinez (2016). Effect of net size on estimates of abundance, size/age, and sex of Mysis diluviana. Journal of Great Lakes Research, Volume 42, Issue 3, June 2016 [[paper]](http://www.sciencedirect.com/science/article/pii/S038013301600040X?via%3Dihub) [[R code on gitHub]](http://jtipton25.github.io/mysis/)

* [4] John Tipton, Jean Opsomer, and Gretchen Moisen (2013). Properties of endogenous post-stratified estimation using remote sensing data. Remote Sensing of Environment, 139:130-137. [[pdf]](https://www.fs.fed.us/rm/pubs_other/rmrs_2013_tipton_j001.pdf)

* [3] John Tipton, Gretchen Moisen, Paul Patterson, and Thomas Jackson (2012). Sampling intensity and normalization: Exploring cost-driving factors in nationwide mapping of tree canopy cover. In: McWilliams, Will and Roesch, Frank, (compilers). 2010 Forest Inventory and Analysis (FIA) Symposium. [[pdf]](https://www.srs.fs.fed.us/pubs/gtr/gtr_srs157/gtr_srs157_201.pdf)

* [2] Thomas Jackson, Gretchen Moisen, Paul Patterson and John Tipton (2012). Repeatability in photo-interpretation of tree canopy cover and its effect on predictive mapping. In:McWilliams, Will and Roesch, Frank, (compilers). 2010 Forest Inventory and Analysis (FIA) Symposium. [[pdf]](https://www.srs.fs.fed.us/pubs/gtr/gtr_srs157/gtr_srs157_189.pdf)

* [1] David Gammon, Myron Baker, and John Tipton (2005). Cultural divergence within novel song in the black-capped chickadee (Poecile atricapillus). The Auk, 122, 853-871. [[paper]](http://www.bioone.org/doi/abs/10.1642/0004-8038%282005%29122%5B0853%3ACDWNSI%5D2.0.CO%3B2)


## In Preparation

* John Tipton, Basil Davis, Manuel Chevalier, and Philipp Sommer. Spatio-temporal reconstruction of climate from pollen. 

* Kelly Heilman, Jason McLachlan, A. Carla Staver, John W.Williams, David Mladenoff, Simon Goring, Christopher J. Paciorek, and John Tipton. Loss of temperate savanna-forest bistability due to changes in land-use.

* John Tipton, Basil Davis, Manuel Chevalir, and Philipp Sommer. Improving pollen reconstructions of climate using Polya-gamma data augmentation.

* John Tipton. Making Bayesian spatio-temporal models conjugate through recursive Bayesian inference.

# Presentations

## Invited



* 2019 -- November -- Presentation - University of Arkansas Industrial Engineering INFORMS Seminar:  Reducing the computational cost for Bayesian modeling of non-Gaussian, noisy spatio-temporal data

* 2019 -- July -- Poster - Institute of Mathematical Statistics New Researchers Conference: Spatio-temporal reconstruction of climate from pollen data

* 2019 -- April -- Presentation - University of Missouri Statistics Department: Spatio-temporal reconstruction of climate from pollen data 

* 2018 -- November -- Presentation - University of Arkansas Department of Geosciences: Don't let your statistics ruin the science that you love

* 2018 -- September -- Presentation - Kansas State University Statistics Department: Spatio-temporal reconstruction of climate from pollen data

* 2018 -- September -- Presentation - University of Arkansas Statistics Seminar: Spatio-temporal reconstruction of climate from pollen data

* 2017 -- August -- Poster - ASA: Bayesian Multispecies Ecological Models for Paleoclimate Reconstruction Using Inverse Prediction

* 2015 -- August -- Presentation - ASA: ENVR Student Paper Award: Reconstruction of late Holocene climate based on tree growth and mechanistic hierarchical models

* 2015 -- August -- Poster - ASA STATMOS: Reconstruction of late Holocene climate based on tree growth and mechanistic hierarchical models

* 2014 -- December -- Presentation - American Geophysical Union: A statistical reconstruction of bivariate climate from tree ring measurements using scientifically motivated process models

## Contributed

* 2019 -- August -- Presentation - ASA: Spatio-temporal reconstruction of climate from pollen data

* 2018 -- August -- Presentation - ASA: Modeling Sediment Mixing using Mixtures of Dirichlet Processes

* 2017 -- August -- Presentation - ASA: Reconstruction of Spatio-Temporal Temperature from Sparse Historical Records Using Robust Probabilistic Principal Component Regression

* 2017 -- December -- Poster: American Geophysical Union - co-author: Comparing and improving reconstruction methods for proxies based on compositional data

* 2017 -- December -- Presentation: American Geophysical Union - co-author: Inferring biogeochemistry past: a millennial-scale multimodel assimilation of multiple paleoecological proxies

* 2017 -- December -- Presentation: American Geophysical Union - co-author: Uncertainty and inference in the world of paleoecological data

* 2016 -- August -- Presentation - ASA: Inverting the Gaussian process: A Bayesian multispecies ecological model for paleoclimate reconstruction

* 2016 -- August -- Poster - ASA: Robust spatio-temporal reconstruction of temperature processes from sparse historical data

* 2014 -- December -- Poster - American Geophysical Union - co-author: Effects of European land use on contemporary tree-climate relationships in the northeastern United States: Implications for predictive models

* 2014 -- August -- Presentation - ASA: Reconstruction of historical climate using a reduced rank predictive process model

* 2012 -- August -- Presentation - ASA: Endogenous post-stratification using random forests

* 2012 -- December -- Presentation - Forest Inventory and Analysis Symposium: Properties of the endogenous post-stratified estimator using a random forest model


# Funding

## External

* 2019-2024 -- National Science Foundation. Multidisciplinary Data Science Education to Prepare STEM Students for Data Science Careers Award: DUE 1930532 \$1,000,000 (role: Senior Personnel)

### Not Funded

## Internal 

* 2019-2022 -- University of Arkansas Chancellor's Grant. Computational Capsule Neural Network Algorithms for Enabling Terahertz Detection of Breast Cancer. \$53,197 (role: co-PI)


<!-- % \section{Research Experience} -->
<!-- %  -->
<!-- % %\subsection{Vocational} -->
<!-- %  -->
<!-- % \cventry{2017-present}{Assistant Professor}{University of Arkansas}{}{}{Developed Bayesian hierarchical models for reconstruction of paleoclimate using proxy data. -->
<!-- % \newline{}\newline{} -->
<!-- % Detailed achievements: -->
<!-- % \begin{itemize} -->
<!-- % \item Spatio-temporal prediction of climate from complex pollen data -->
<!-- % \begin{itemize} -->
<!-- % \item Predict missing climate states from compositional pollen data -->
<!-- % \item Estimate high-dimensional, dynamic latent climate state efficiently withn MCMC -->
<!-- % \item Account for uncertainty in temporal dating of observations -->
<!-- % \end{itemize} -->
<!-- % \item Predictive model comparison for multivariate count data -->
<!-- % \begin{itemize} -->
<!-- % \item Predict missing covariates in regression model -->
<!-- % \item Evaluate predictive skill using proper scoring rules -->
<!-- % \item Criticize model performance under a variety of real-world assumptions -->
<!-- % \end{itemize} -->
<!-- % \item Bayesian nonparametric estimation of sediment age distributions -->
<!-- % \begin{itemize} -->
<!-- % \item Dirichlet process mixture model for sediment distributions -->
<!-- % \item Generate unsupervised predictions of unobserved distribution given mixture distributions -->
<!-- % \item Improvement over current non-negative factorization methods by providing principled estimation of uncertainty -->
<!-- % \end{itemize} -->
<!-- % \end{itemize}} -->
<!-- % \vspace{0.25cm} -->
<!-- %  -->
<!-- %  -->
<!-- % \cventry{2016--2017}{Postdoctoral Researcher}{\textsc{PalEON}}{}{}{Developed Bayesian hierarchical models for reconstruction of paleoclimate using proxy data. -->
<!-- % \newline{}\newline{} -->
<!-- % Detailed achievements: -->
<!-- % \begin{itemize} -->
<!-- % \item Spatially explicit reconstruction of average July temperature in the U.S. -->
<!-- % \begin{itemize} -->
<!-- % \item Data from historical military fort records -->
<!-- % \item EOF regression with spatial random effects -->
<!-- % \item Model selection techniques to provide shrinkage of estimates -->
<!-- % \item Validation of predictive ability in a simulation experiment -->
<!-- % \end{itemize} -->
<!-- % \item Inverse Gaussian Process models for prediction of latent climate given species composition data -->
<!-- % \begin{itemize} -->
<!-- % \item Data from testate Amoeba in peat bogs -->
<!-- % \item Gaussian Process regression model where the covariate location is to be predicted -->
<!-- % \item Dimension reduction for computational efficiency -->
<!-- % \end{itemize} -->
<!-- % \end{itemize}} -->
<!-- % \vspace{0.25cm} -->
<!-- %  -->
<!-- % \cventry{2013--2016}{Graduate Research Assistant}{\textsc{PalEON}}{}{}{Developed Bayesian hierarchical models for reconstruction of paleoclimate using proxy data. -->
<!-- % \newline{}\newline{} -->
<!-- % Detailed achievements: -->
<!-- % \begin{itemize} -->
<!-- % \item Reconstruction of temperature and precipitation from tree rings -->
<!-- % \begin{itemize} -->
<!-- % \item Data assimilation from different sources and scales in the Hudson Valley, New York -->
<!-- % \item Extension of cutting edge modeling techniques to increase predictive skill -->
<!-- % \item Use of model selection to choose between non-linear process models for tree ring growth -->
<!-- % \end{itemize} -->
<!-- % \end{itemize}} -->
<!-- % \vspace{0.25cm} -->
<!-- % %------------------------------------------------ -->
<!-- % \cventry{2009--2013}{Graduate Research Assistant}{\textsc{United States Forest Service}}{}{}{Research on sampling methods for pilot study of tree canopy cover and application of state of the art survey sampling methodologies to aid in development of the National Land Cover Database. -->
<!-- % \newline{}\newline{} -->
<!-- % Detailed achievements: -->
<!-- % \begin{itemize} -->
<!-- % \item Inclusion of powerful machine learning methods in a statistical framework -->
<!-- % \item Analysis of remote sensing and statistical techniques for creation of land cover maps -->
<!-- % \item Sample size and power calculations to improve sampling methods and decrease cost -->
<!-- % \end{itemize}} -->

<!-- %------------------------------------------------ -->
<!-- %------------------------------------------------ -->
<!-- %------------------------------------------------ -->
<!-- % \pagebreak -->
<!-- %------------------------------------------------ -->
<!-- %------------------------------------------------ -->
<!-- %------------------------------------------------ -->


<!-- %------------------------------------------------ -->
<!-- %---------------------------------------------------------------------------------------- -->
<!-- %	TEACHING EXPERIENCE SECTION -->
<!-- %---------------------------------------------------------------------------------------- -->

# Teaching Experience

## University of Arkansas

Responsible for course redesign and/or development for DASC 1104, DASC 2594, STAT 3003, STAT 4003, STAT 4043, STAT 5003 STAT 5383, and STAT 5413. Also a member of the data science curriculum development committee developing 54 new credit hours and a member of the data science advisory board. As a member of the data science curriculum committee, I created lesson and unit plans for DASC 1104 Programming Languages for Data Sciene, DASC 2594 Multivariable Math for Data Scientists, and DASC 3213 Statistical Learning

* DASC 1104 Programming Languages for Data Science (Fall 2020)
* DASC 2594 Multivariable Math for Data Scientists (Spring 2021)
* STAT 2303 Principles of Statistics (Fall 2017)
* STAT 3003 Statistical Methods (Spring 2021) 
* STAT 5383 Time Series (Fall 2017) 
* STAT 4043 Survey Sampling (Spring 2018, Spring 2019) 
* STAT 4003 Statistical Methods (Fall 2018, Spring 2019, Fall 2019) 
* STAT 5003 Statistical Methods (Spring 2020, Fall 2020) 
* STAT 5413 Spatial Statistics (Spring 2020) 


## Colorado State University

### Instructor

* STAT 307 Intro to Biostatistics, three semesters 
* STAT 204 Business Statistics, two semesters 

### Teaching assistant

* STAT 472 Statistical Consulting, one semester 
* STAT 301 Intro to Statistics Online, one semester 
* STAT 204 Business Statistics, one semester 

### Workshops

* Building Capacity in Bayesian Modeling for Ecologists (NSF), 2 days \hfill 2014, 2016
* Workshop on Parallel Computing, CU/CSU, \hfill 2015
* R Workshop (CSU-CCFRWU), 1 day \hfill 2013, 2015

# Service
* 2017-2020: Interdisciplinary committee for the creation of an undergraduate degree in data science
* 2019-present: Department of Mathematical Sciences undergraduate curriculum committee
* 2019-present: Data science undergraduate curriculum committee


# Honors/Awards

* University of Arkansas New Faculty Commendation for Teaching Commitment \hfill 2018
* Colorado State University Statistics Department Poster Symposium - Best Poster \hfill 2016
* American Statistical Association ENVR Student Paper Competition Award \hfill 2015
* Thomas J. and Eileen C. Boardman Statistical Consulting Award \hfill 2014
* American Statistical Association Student Travel Award \hfill 2014
* American Statistical Association Wray Jackson Smith Award \hfill 2012

# Software and Computing

## R packages

* [R package BayesMRA -- available on CRAN](https://github.com/jtipton25/BayesMRA) \hfill 2020
* [gitHub R package Bayescomposition](https://github.com/jtipton25/BayesComposition) \hfill 2019
* [gitHub R package stPollen](https://github.com/jtipton25/stPollen) \hfill 2019

## Data Tutorials and Reproducibility

* [GitHub tutorial](https://github.com/jtipton25/compositional-inverse-prediction/) for: John Tipton, Mevin Hooten, Connor Nolan, Bob Booth, and Jason McLachlan. (2019) Predicting unobserved climate from compositional data using multivariate Gaussian process inverse prediction. \textit{Annals of Applied Statistics}

* [GitHub tutorial](https://jtipton25.github.io/mysis/) for: Douglas Silver, Brett Johnson, William Pate, Kyle Christianson, John Tipton, James Sherwood, Brian Smith, Yun Hao, and Patrick Martinez. (2016). Effect of net size on estimates of abundance, size/age, and sex of \textit{Mysis diluviana}. \textit{Journal of Great Lakes Research}, Volume 42, Issue 3.

* [GitHub tutorial and R software](https://github.com/jtipton25/Mechanistic-Tree-Ring) for: John Tipton, Mevin Hooten, Neil Pederson, Martin Tingley and Daniel Bishop. (2016). Reconstruction of late Holocene climate based on tree growth and mechanistic hierarchical models. \textit{Environmetrics}, 27(1):42-54. 


## Computing Expertise


\begin{multicols}{3}
\begin{itemize}
\item \textsc{R} 
\item \textsc{C++}
\item \LaTeX 
\item \textsc{Linux}
\item \textsc{python}
\end{itemize}
\end{multicols}


# Student Advising

<!-- ## Postdoctoral Fellows (Current) -->
<!-- ## Postdoctoral Fellows (Former) -->

## Graduate Students (Current)

* Jean Remy Habima (PhD-Mathematics), Adviser
* Surya Lamichhane (PhD-Mathematics), Committee Member
* Muhenned Abdulasalim (MS-STAN), Adviser
* Thuy Scanlon (MS-STAN), Adviser
* Ariel Mundo (PhD-Biomedical Engineer), Committee Member
* Leah Bayer (PhD-Biology), Committee Member
* Chang Liu (PhD-Environmental Dynamics), Proposal Committee Member

## Graduate Students (Graduated)

* Pauline Morin (MS-Food Science), Committee Member \hfill 2020
* Seyed Tabari (MS-STAN), Committee Member \hfill 2020
* Philipp Sommer (PhD-Geosciences, University of Lausanne), \textbf{Examiner} \hfill 2019
* Ruizhe (Rachel) Yin (MS-STAN), \textbf{Committee Chair} \hfill 2019
* Hua Zhong (MS-STAN), \textbf{Committee Chair} \hfill 2019
* Michael Harris (MS-STAN), Committee Member \hfill 2019
* Josh Price (MS-STAN), Committee Member \hfill 2019
* Md Kamrul Hasan Khan (MS-STAN), Committee Member \hfill 2018
* Kai Cui (MS-STAN), Committee Member \hfill 2018
* Michael Ellis (MS-STAN), Committee Member \hfill 2018


## Undergraduate Students

* Abigail Rhodes (Honors)
* Caleigh Christensen (Honors)
* Brenna Frandson (Honors)


# Manuscript Peer Review

Annals of Applied Statistics (4 times); Computational Statistics and Data Analysis (2 times); Environmental and Ecological Statistics (1 time); Journal of Agricultural, Biological, and Environmental Statistics (3 times); Journal of Geophysical Research - Biogeosciences (1 time); Ecological Applications (1 time); Freshwater Science (1 time); Climate of the Past (1 time); Chemical Geology (1 time); Arctic, Antarctic, and Alpine Research (1 time); Science (1 time); Nature Communications (1 time)
